export const ADMIN_TEXTS = {
	ADMIN_PANEL_TITLE: "⚙️ Админ-панель",
	AAA_STORE_PRICE: "📤 Загрузить aaa-store прайс",
	TODAY_THERE_TOMORROW_HERE_PRICE: "📤 Загрузить прайс сегодня там, завтра тут",
	MANAGE_USERS: "👥 Управление пользователями",
	UPLOAD_XLSX_MESSAGE: "📎 *Загрузить XLSX*\n\n" +
		"Пожалуйста, отправьте файл в формате `.xlsx`.\n" +
		"После загрузки я обработаю данные.",
  PRICE_UPLOAD_SUCCESS: "✅ Прайс успешно загружен\n",
  PRICE_UPLOAD_TOTAL_ROWS: "Товаров в прайсе: ",
  PRICE_UPLOAD_TOTAL_ITEMS: "Всего товаров: ",
  PRICE_UPLOAD_NEW_ITEMS: "\nНовых товаров: ",
  PRICE_UPLOAD_UPDATED_ITEMS: "\nОбновлено товаров в каталоге: ",
  ITEMS_WITHOUT_MARKUP: "\n\n⚠️ Товары без наценки  - ",
  ITEMS_WITH_UNKNOWN_BRAND: "⚠️ Не удалось определить бренд - ",
	EDIT_RUB_TO_BYN: "RUB/BYN: ",
	EDIT_RUB_TO_USD: "RUB/USD: ",
	EDIT_USD_TO_BYN: "USD/BYN: ",
  RENEW_PRICE: "🌀 Обновить конфиг",
	DONT_WAITING_FILE: "⛔ Сейчас я не жду файл",
	AI_ERROR: "⚠️ ОШИБКА ИИ",
	AI_COST: "💰 Стоимость AI-запросов: $",
	DONT_RECOGNIZED: "❌ НЕ РАСПОЗНАНЫ",
	CANT_FIND_FILE: "❌ Файл не найден",
	ERROR_ITEMS: "❌ Файл не содержит валидных товаров",
	ERROR_XLSX: "❌ XLSX upload error: ",
	FILE_ERROR: "❌ Ошибка при обработке файла",
  RENEW_PRICE_SUCCESS: "💸 Конфиг успешно обновился",
	RENEW_PRICE_ERROR: "❌ Ошибка при обновлении конфига",

	CHECK_RAWNAMES: "🔍 Товары с дублями rawNames",

	APPLE_SIM_PAGE_CHANGED: "🍏 Apple обновила страницу про типы SIM в iPhone",
	APPLE_SIM_PAGE_HINT: "Проверь, не нужно ли поправить normalizeSimByRules и списки стран в types/product.ts",
	APPLE_SIM_PAGE_ADDED: "➕ Добавлено:",
	APPLE_SIM_PAGE_REMOVED: "➖ Удалено:",
	APPLE_SIM_PAGE_PARSE_ERROR: "⚠️ Не удалось разобрать страницу Apple про типы SIM — возможно, поменялась вёрстка. Проверь вручную:",
};
