export const ADMIN_TEXTS = {
	ONLY_ADMINS: "⛔ Только для администраторов",
	UPLOAD_XLSX: "📤 Загрузить XLSX",
	MANAGE_USERS: "👥 Управление пользователями",
	UPLOAD_XLSX_MESSAGE: "📎 *Загрузить XLSX*\n\n" +
		"Пожалуйста, отправьте файл в формате `.xlsx`.\n" +
		"После загрузки я обработаю данные.",
  PRICE_UPLOAD_SUCCESS: "✅ Прайс успешно загружен\nТоваров: ",
  MANAGE_USERS_MESSAGE: "👨‍💼 *Управление пользователями*\n\nВыберите действие:",
	ADD_USER_BTN: "➕ Добавить пользователя",
	DELETE_USER_BTN: "➖ Удалить пользователя",
  EDIT_USER_BTN: "🤖🔧Редактировать пользователя",
	DELETE_USER_TEXT: "🗑 Введи ID пользователя, которого нужно удалить:",
	USERS_LIST: "📋 Список пользователей",
	EDIT_RUB_TO_BYN: "💱 Курс к BYN: ",
	EDIT_RUB_TO_USD: "💱 Курс к USD: ",
  RENEW_PRICE: "🌀 Обновить цены",
	DONT_WAITING_FILE: "⛔ Сейчас я не жду файл",
	CANT_FIND_FILE: "❌ Файл не найден",
	ERROR_ITEMS: "❌ Файл не содержит валидных товаров",
	ERROR_XLSX: "❌ XLSX upload error: ",
	FILE_ERROR: "❌ Ошибка при обработке файла",
  RENEW_PRICE_SUCCESS: "💸 Цены успешно обновились",
	RENEW_PRICE_ERROR: "❌ Ошибка при обновлении цен",
};